// MCP wrapper extension for pi.dev.
//
// Reads ./servers.json (generated by sync-pi.sh from mcp.json) and registers
// one meta-tool per HTTP MCP server. Each meta-tool exposes three actions:
//   - list_tools: enumerate tools the server provides
//   - describe_tool: fetch the JSON schema for a specific tool
//   - call_tool: invoke a tool with arguments
//
// Pattern is modeled on DataDog/experimental#9833 (Michael Borst's slack-mcp
// wrapper). Keeping the schema out of the agent context (only loaded on
// describe_tool) cuts the per-server token cost from ~46 KB to ~2 KB.
//
// Limitations (v1):
//   - HTTP transport only; no stdio child processes
//   - OAuth-flow servers (slack) need a pre-acquired bearer token in
//     PI_MCP_<SERVER>_TOKEN env (e.g. PI_MCP_SLACK_TOKEN)
//   - No streaming responses surfaced to the agent; we collect the full reply

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

type ServerConfig = {
  name: string;
  url: string;
  oauth?: { clientId: string; callbackPort: number };
};

type Manifest = { servers: ServerConfig[] };

type JsonRpcRequest = {
  jsonrpc: "2.0";
  id: number;
  method: string;
  params?: unknown;
};

type JsonRpcResponse = {
  jsonrpc: "2.0";
  id: number;
  result?: unknown;
  error?: { code: number; message: string; data?: unknown };
};

const HERE = dirname(fileURLToPath(import.meta.url));

function loadManifest(): Manifest {
  const path = join(HERE, "servers.json");
  return JSON.parse(readFileSync(path, "utf8")) as Manifest;
}

function bearerFromEnv(serverName: string): string | undefined {
  const key = `PI_MCP_${serverName.toUpperCase().replace(/-/g, "_")}_TOKEN`;
  return process.env[key];
}

// Tokens that suggest a tool mutates state. Used to gate write tools through
// ctx.ui.confirm before calling. False positives are fine, false negatives are
// the risk we want to avoid.
const WRITE_VERBS = /\b(create|update|delete|add|remove|send|post|edit|set|patch|put|move|transition|run|trigger|execute)\b/i;

class McpClient {
  private nextId = 1;
  private sessionId: string | undefined;
  private initialized = false;

  constructor(private readonly server: ServerConfig) {}

  private headers(): Record<string, string> {
    const h: Record<string, string> = {
      "Content-Type": "application/json",
      Accept: "application/json, text/event-stream",
    };
    if (this.sessionId) h["mcp-session-id"] = this.sessionId;
    const token = bearerFromEnv(this.server.name);
    if (token) h["Authorization"] = `Bearer ${token}`;
    return h;
  }

  private async post(method: string, params?: unknown): Promise<unknown> {
    const body: JsonRpcRequest = {
      jsonrpc: "2.0",
      id: this.nextId++,
      method,
      params,
    };
    let res = await fetch(this.server.url, {
      method: "POST",
      headers: this.headers(),
      body: JSON.stringify(body),
    });

    // One-shot retry on 401/404 with a fresh session.
    if ((res.status === 401 || res.status === 404) && this.sessionId) {
      this.sessionId = undefined;
      this.initialized = false;
      res = await fetch(this.server.url, {
        method: "POST",
        headers: this.headers(),
        body: JSON.stringify(body),
      });
    }

    const newSid = res.headers.get("mcp-session-id");
    if (newSid) this.sessionId = newSid;

    if (!res.ok) {
      throw new Error(`MCP ${this.server.name} ${method}: HTTP ${res.status} ${res.statusText}`);
    }

    const text = await res.text();
    const parsed = parseStreamableHttp(text);
    if (parsed.error) {
      throw new Error(`MCP ${this.server.name} ${method}: ${parsed.error.message}`);
    }
    return parsed.result;
  }

  private async ensureInitialized(): Promise<void> {
    if (this.initialized) return;
    await this.post("initialize", {
      protocolVersion: "2025-03-26",
      capabilities: {},
      clientInfo: { name: "code-factory-mcp-wrapper", version: "0.1.0" },
    });
    this.initialized = true;
  }

  async listTools(): Promise<Array<{ name: string; description?: string }>> {
    await this.ensureInitialized();
    const result = (await this.post("tools/list")) as { tools?: Array<{ name: string; description?: string }> };
    return result.tools ?? [];
  }

  async describeTool(name: string): Promise<unknown> {
    await this.ensureInitialized();
    const result = (await this.post("tools/list")) as { tools?: Array<{ name: string; description?: string; inputSchema?: unknown }> };
    const found = (result.tools ?? []).find((t) => t.name === name);
    if (!found) throw new Error(`Tool not found: ${name}`);
    return found;
  }

  async callTool(name: string, args: Record<string, unknown>): Promise<unknown> {
    await this.ensureInitialized();
    return this.post("tools/call", { name, arguments: args });
  }
}

// Parse a streamable-HTTP response body. Servers return either a single
// JSON-RPC object or an SSE stream of `data: {...}\n\n` frames. We only need
// the final result/error.
function parseStreamableHttp(body: string): JsonRpcResponse {
  const trimmed = body.trim();
  if (trimmed.startsWith("{")) {
    return JSON.parse(trimmed) as JsonRpcResponse;
  }
  // SSE: take the last non-empty `data:` frame.
  const frames = trimmed
    .split(/\n\n+/)
    .map((f) => {
      const dataLine = f.split("\n").find((l) => l.startsWith("data:"));
      return dataLine ? dataLine.slice(5).trim() : "";
    })
    .filter(Boolean);
  if (frames.length === 0) {
    throw new Error("MCP response was empty");
  }
  return JSON.parse(frames[frames.length - 1]) as JsonRpcResponse;
}

export default function register(pi: ExtensionAPI): void {
  const manifest = loadManifest();
  if (manifest.servers.length === 0) {
    return;
  }

  for (const server of manifest.servers) {
    const client = new McpClient(server);
    const toolName = server.name.replace(/-/g, "_");

    pi.registerTool({
      name: toolName,
      label: `${server.name} (MCP)`,
      description: `Call the ${server.name} MCP server. Use action=list_tools first to discover available tools, then describe_tool to fetch a tool's input schema, then call_tool to invoke it.`,
      // Plain JSON Schema. Pi accepts any object that conforms; we avoid the
      // @sinclair/typebox dependency by hand-writing it.
      parameters: {
        type: "object",
        properties: {
          action: {
            type: "string",
            enum: ["list_tools", "describe_tool", "call_tool"],
            description: "list_tools to enumerate, describe_tool to inspect schema, call_tool to invoke",
          },
          tool: { type: "string", description: "Tool name (required for describe_tool and call_tool)" },
          args: { type: "object", additionalProperties: true, description: "Arguments for call_tool" },
        },
        required: ["action"],
      } as any,
      async execute(_id, params, _signal, _onUpdate, ctx) {
        const { action, tool, args } = params as {
          action: "list_tools" | "describe_tool" | "call_tool";
          tool?: string;
          args?: Record<string, unknown>;
        };

        try {
          if (action === "list_tools") {
            const tools = await client.listTools();
            return { content: JSON.stringify(tools, null, 2) };
          }
          if (action === "describe_tool") {
            if (!tool) return { isError: true, content: "tool is required for describe_tool" };
            const desc = await client.describeTool(tool);
            return { content: JSON.stringify(desc, null, 2) };
          }
          if (action === "call_tool") {
            if (!tool) return { isError: true, content: "tool is required for call_tool" };

            // Gate likely-write tools through a UI confirmation.
            if (WRITE_VERBS.test(tool) && !process.env.PI_MCP_AUTOAPPROVE) {
              const approved = await ctx.ui.confirm({
                title: `${server.name}: ${tool}`,
                description: `Call ${tool} with: ${JSON.stringify(args ?? {})}`,
              });
              if (!approved) {
                return { isError: true, content: "User declined the tool call." };
              }
            }

            const result = await client.callTool(tool, args ?? {});
            return { content: JSON.stringify(result, null, 2) };
          }
          return { isError: true, content: `Unknown action: ${action}` };
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          return { isError: true, content: msg };
        }
      },
    });
  }

  pi.on("session_shutdown", () => {
    // Per-server client instances drop their session id; nothing else to clean
    // up since we don't hold open sockets.
  });
}
